language: python
python:
  - '3.6'

env:
  - DJANGO_ENV=Testing

services:
  - postgresql

before_script:
  - pip install -r requirements.txt
  - pip install coveralls
  - psql -c 'create database authors;' -U postgres
  - python manage.py makemigrations 
  - python manage.py migrate 

script:
  - pytest -v --cov=authors --cov-report=term-missing

after_success:
  - coveralls
