language: python
python:
  - "3.6"

env:
  - DJANGO_ENV=Testing

services:
  - postgresql

before_script:
  - pip install -r requirements.txt
  - pip install coveralls
  - psql -c 'create database authors;' -U postgres
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput
  
script:
  - python manage.py test
  - coverage run --source='.' manage.py test

after_success:
  - coveralls